### ISSUE TITLE
SINTESIS Webinar Gratuito | "Buenas prácticas en Gestión de Proyectos"

### ISSUE THREAD

**Issue by JudithReynaCS** [SistemasTecTlaxiaco/actividad-3-sintesis-JudithReynaCS#2]
[SINTESIS_JUDITHREYNACRUZSANTIAGO_7US.pdf](https://github.com/SistemasTecTlaxiaco/actividad-3-sintesis-JudithReynaCS/files/12530108/SINTESIS_JUDITHREYNACRUZSANTIAGO_7US.pdf)

**Comment by EdwinOrtiz1412** [comment]
20%

**Comment by josealfredo79** [comment]
Bien hecho y revisado..
